[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lottery = "ytKyH7viyfRmqYtS7Y3nCa8kCJXAPTN6MA8a3EmtSn1"  # Updated with new program ID
lp_manager = "G5WidJNwmdp33kQ6AeTcrsKJdP9rvuecfyZXCmQ6oSNG"
pepball_token = "HArmxo4FBfy7RiT3iS7erxvC23L1AreU9AskyXc3iuhR"

[programs.localnet]
lottery = "ytKyH7viyfRmqYtS7Y3nCa8kCJXAPTN6MA8a3EmtSn1"
lp_manager = "G5WidJNwmdp33kQ6AeTcrsKJdP9rvuecfyZXCmQ6oSNG"
pepball_token = "HArmxo4FBfy7RiT3iS7erxvC23L1AreU9AskyXc3iuhR"

[programs.mainnet]
lottery = "11111111111111111111111111111111"
lp_manager = "11111111111111111111111111111111"
pepball_token = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
